### ISSUE TITLE
Both GenerateSW and InjectManifest run forever on dev compile, crash on build

### ISSUE THREAD

**Issue by jakemmarsh** [hanford/next-offline#115]
I'm on next.js `7.0.2`, next-offline `3.3.4`, and webpack `4.21.0`.

I'm using this plugin alongside various others via `next-compose-plugins`. The relevant portion of my `next.config.js` looks something like this:

```
module.exports = withPlugins([
  ...,
  [withOffline, {
    generateInDevMode: true,
  }]
], {
  webpack(config, { dev, isServer, buildId }) {
    ...
    
    return config;
  }
});
```

When running my app in dev, `GenerateSW` (or `InjectManifest` if I change the config to use that) both run forever and so my client compilation is stuck at 95% until I stop the process.

When running the build for production, I get a separate error inside `workbox-webpack-plugin`:

```
> Failed to build
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type object
    at Hash.update (internal/crypto/hash.js:58:11)
    at module.exports (/Users/jakemarsh/repos/monolist/web-client/node_modules/workbox-webpack-plugin/build/lib/get-asset-hash.js:28:35)
    at generateMetadataForAssets (/Users/jakemarsh/repos/monolist/web-client/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js:239:15)
    at getManifestEntriesFromCompilation (/Users/jakemarsh/repos/monolist/web-client/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js:317:23)
    at InjectManifest._callee$ (/Users/jakemarsh/repos/monolist/web-client/node_modules/workbox-webpack-plugin/build/inject-manifest.js:146:27)
```

Am I doing something wrong here?

**Comment by hanford** [comment]
Hmmm, I actually haven't really used `generateInDevMode` much. A contributor added that flag .. 🤔 Could you try a deploy without it?

Could you share more about your project? Perhaps a repo where this issue is reproducible? That would help me dive a little deeper

**Comment by williamluke4** [comment]
I'm having the same issue.. @jakemmarsh Did you find a workaround?

**Comment by jakemmarsh** [comment]
@williamluke4 unfortunately not. I also tried using `workbox-webpack-plugin` directly and ran into the same problems, so the issue does seem to be there. I resorted to just writing my service worker from scratch and loading workbox manually.
