### ISSUE TITLE
Now Build Warnings?

### ISSUE THREAD

**Issue by NathanielHill** [hanford/next-offline#117]
Don't know if this is related, but opening this issue for visibility/diagnosis...

I'm getting the following warning in my Now 2.0 logs:

```
> Emitted warnings from webpack

You're using the following Workbox configuration options: [globDirectory, globPatterns]. In Workbox v3 and later, this is usually not needed. Please see https://goo.gl/EQ4Rhm for more info. One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": ".",
  "globPattern": "static/**/*",
  "globIgnores": [
    "**/node_modules/**/*"
  ]
} ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
    at Compilation.reportDependencyErrorsAndWarnings (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/Compilation.js:1359:23)
    at Compilation.finish (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/Compilation.js:1165:9)
    at hooks.make.callAsync.err (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/Compiler.js:544:17)
    at _err0 (eval at create (/tmp/79ec3e9e/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at Promise.all.then (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/DynamicEntryPlugin.js:74:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at CommonJsRequireContextDependency.getWarnings (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/Compilation.js:1354:24)
    at Compilation.finish (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/Compilation.js:1165:9)
    at hooks.make.callAsync.err (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/Compiler.js:544:17)
    at _err0 (eval at create (/tmp/79ec3e9e/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at Promise.all.then (/tmp/79ec3e9e/node_modules/next/node_modules/webpack/lib/DynamicEntryPlugin.js:74:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

`next-offline` is the only thing explicitly using WorkBox in my project...
Any ideas?

**Comment by hanford** [comment]
@NathanielHill ahh I thought this was fixed. Just double checking you're on latest `v3.3.5`

It's a warning, we basically are using some field that they are trying to deprecate .. but IIRC we're getting functionality from having those fields there..

If you're in fact on the latest, let me know and I'll try modifying some projects removing `globDirectory` and `globPattern` and if functionality is the same I can cut a new release without those flags

**Comment by NathanielHill** [comment]
Yup, I'm on `v3.3.5`. If the options are necessary, perhaps there's a way to silence the warnings?

**Comment by hanford** [comment]
Been swamped at work this week, sorry for going dark!

**Comment by hanford** [comment]
This might get addressed once Workbox 4.0 comes out https://github.com/hanford/next-offline/issues/62

I quickly glanced at the 3.0.0 API and couldn't find away to silence warnings 🤔

**Comment by NathanielHill** [comment]
FYI @hanford This now occurs on the command line as well:

```
$ next build

✔ Client
  Compiled successfully in 19.27s

✔ Server
  Compiled successfully in 6.05s

> Using external babel configuration
> Location: "/home/user/app/package.json"
> Emitted warnings from webpack
You're using the following Workbox configuration options: [globDirectory, globPatterns]. In Workbox v3 and later, this is usually
 not needed. Please see https://goo.gl/EQ4Rhm for more info.
One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": ".",
  "globPattern": "static/**/*",
  "globIgnores": [
    "**/node_modules/**/*"
  ]
}
 ┌ /
 ├ /_app
 ├ /_document
 └ /_error
```

**Comment by hanford** [comment]
👍 - still planning on punting until workbox 4! Been very busy lately

**Comment by hanford** [comment]
Closing this due to inactivity .. if this is still happening please open a new issue!
