### ISSUE TITLE
Webpack error when adding the devSwSrc parameter

### ISSUE THREAD

**Issue by srosset81** [hanford/next-offline#142]
If I set the `devSwSrc` parameter to next-offline, I get the following error in dev mode :

```
(node:11338) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'issuer' of undefined
    at findEntryModule (/home/sebastien/Hozana/hozana.org-v2/node_modules/next/dist/server/hot-reloader.js:64:14)
    at erroredPages (/home/sebastien/Hozana/hozana.org-v2/node_modules/next/dist/server/hot-reloader.js:85:25)
    at HotReloader._callee8$ (/home/sebastien/Hozana/hozana.org-v2/node_modules/next/dist/server/hot-reloader.js:822:31)
    at tryCatch (/home/sebastien/Hozana/hozana.org-v2/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/sebastien/Hozana/hozana.org-v2/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/home/sebastien/Hozana/hozana.org-v2/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/home/sebastien/Hozana/hozana.org-v2/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/home/sebastien/Hozana/hozana.org-v2/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
```
If I remove the  `devSwSrc` parameter, everything works fine again.

I don't know where this error is coming from, but it is certainly linked to webpack, which has a lot of `issuer` properties.

**Comment by hanford** [comment]
The current development work flow is super buggy. It was a total after thought when making this plugin.

I'd like to revamp it, and if I get some downtime in the near term future I'll spend some time on it.

For now I'd like to track all development work flow related things in this issue: https://github.com/hanford/next-offline/issues/155
