### ISSUE TITLE
Doesn't work with custom project dir

### ISSUE THREAD

**Issue by sarneeh** [hanford/next-offline#183]
1. Create a fresh Next.js project via `npx create-next-app`
2. Install `next-offline`
3. Add `next.config.js` with default `next-offline`
4. Move `pages` to `src/pages`
5. Run `next build src`
6. Error!

`next.config.js`
```js
const withOffline = require("next-offline");

module.exports = withOffline();
```

Error:

```
> next build

Creating an optimized production build ...

(node:30342) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at readFile (fs.js:302:10)
    at go$readFile (/home/jsarnowski/Workshop/next-offline-issue/node_modules/graceful-fs/graceful-fs.js:110:14)
    at readFile (/home/jsarnowski/Workshop/next-offline-issue/node_modules/graceful-fs/graceful-fs.js:107:12)
    at /home/jsarnowski/Workshop/next-offline-issue/node_modules/universalify/index.js:13:12
    at new Promise (<anonymous>)
    at readFile (/home/jsarnowski/Workshop/next-offline-issue/node_modules/universalify/index.js:7:14)
    at /home/jsarnowski/Workshop/next-offline-issue/node_modules/next-offline/next-manifest.js:41:26
    at f (/home/jsarnowski/Workshop/next-offline-issue/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/jsarnowski/Workshop/next-offline-issue/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:203:13)
    at Glob._finish (/home/jsarnowski/Workshop/next-offline-issue/node_modules/glob/glob.js:197:8)
    at done (/home/jsarnowski/Workshop/next-offline-issue/node_modules/glob/glob.js:182:14)
    at Glob._processReaddir2 (/home/jsarnowski/Workshop/next-offline-issue/node_modules/glob/glob.js:408:12)
    at /home/jsarnowski/Workshop/next-offline-issue/node_modules/glob/glob.js:371:17
    at RES (/home/jsarnowski/Workshop/next-offline-issue/node_modules/inflight/inflight.js:31:16)
    at f (/home/jsarnowski/Workshop/next-offline-issue/node_modules/once/once.js:25:25)
(node:30342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As you can see the error is throwing at `next-offline/next-manifest.js:41:26`.

### Notes
`next.js`: 9.0.4
`next-offline`: 4.0.3

**Comment by hanford** [comment]
merged the fix into the v4 branch and released v4.0.4

Thanks for the issue/fix!

**Comment by sarneeh** [comment]
@hanford Thank you very much for such a fast response! :)

**Comment by do-diegoortiz** [comment]
@sarneeh Is there a reason to move pages to src/pages? 
I'm having a similar error with the last version, but is not a fresh project.

**Comment by sarneeh** [comment]
@do-diegoortiz No reason, I just like this project structure 😃
