### ISSUE TITLE
Doesn't work if generateInDevMode set to true

### ISSUE THREAD

**Issue by wilmervanheerde** [hanford/next-offline#195]
Error when service worker generation is set to true in development mode

Seems to be related to #183 and #184
### Steps to reproduce:
 1. Create new Next project `npx create-next-app`
 2. Install next-offline `npm install next-offline`
 3. Copy default config from readme into `next.config.js`
 4. Set option `generateInDevMode` to `true`
 5. Launch Next.js in development mode `npm run dev`

### Stacktrace:
```
(node:30875) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at readFile (fs.js:296:3)
    at go$readFile (<rootDir>/node_modules/graceful-fs/graceful-fs.js:110:14)
    at readFile (<rootDir>/node_modules/graceful-fs/graceful-fs.js:107:12)
    at Promise (<rootDir>/node_modules/universalify/index.js:13:12)
    at new Promise (<anonymous>)
    at readFile (<rootDir>/node_modules/universalify/index.js:7:14)
    at glob (<rootDir>/node_modules/next-offline/next-manifest.js:41:26)
    at f (<rootDir>/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (<rootDir>/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:198:13)
    at Glob._finish (<rootDir>/node_modules/glob/glob.js:197:8)
    at done (<rootDir>/node_modules/glob/glob.js:182:14)
    at Glob._processReaddir2 (<rootDir>/node_modules/glob/glob.js:408:12)
    at <rootDir>/node_modules/glob/glob.js:371:17
    at RES (<rootDir>/node_modules/inflight/inflight.js:31:16)
    at f (<rootDir>/node_modules/once/once.js:25:25)
(node:30875) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30875) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Versions:
**next-offline**: 4.0.6
**next**: 9.1.1

**Comment by theJoeBiz** [comment]
I just ran into this too and I assume it's because the README is for the beta version (currently `5.0.0-beta.7`). Running `npm install next-offline@^5.0.0-beta.7` fixed it.

**Comment by wilmervanheerde** [comment]
> I just ran into this too and I assume it's because the README is for the beta version (currently `5.0.0-beta.7`). Running `npm install next-offline@^5.0.0-beta.7` fixed it.

Thank you, that fixed it for me. Using beta version is fine for me, it's not prod code.

**Comment by markbrocato** [comment]
I'm still getting this on 5.0.0-beta.11

```
(node:44063) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at readFile (fs.js:295:10)
    at go$readFile (<rootDir>/node_modules/graceful-fs/graceful-fs.js:110:14)
    at readFile (<rootDir>/node_modules/graceful-fs/graceful-fs.js:107:12)
    at <rootDir>/node_modules/universalify/index.js:13:12
    at new Promise (<anonymous>)
    at readFile (<rootDir>/node_modules/universalify/index.js:7:14)
    at <rootDir>/node_modules/next-offline/next-manifest.js:41:26
    at f (<rootDir>/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (<rootDir>/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:223:5)
    at Glob._finish (<rootDir>/node_modules/glob/glob.js:197:8)
    at done (<rootDir>/node_modules/glob/glob.js:182:14)
    at Glob._processReaddir2 (<rootDir>/node_modules/glob/glob.js:408:12)
    at <rootDir>/node_modules/glob/glob.js:371:17
    at RES (<rootDir>/node_modules/inflight/inflight.js:31:16)
    at f (<rootDir>/node_modules/once/once.js:25:25)
```
