### ISSUE TITLE
Error with Next-offline hosted with Firebase Functions

### ISSUE THREAD

**Issue by 1nullpointer** [hanford/next-offline#64]
Am seeing following error when i try to use firebase functions with next-offline . 

```
TypeError: (0 , _url.default) is not a function
    at functions.https.onRequest (/user_code/app/app.js:32:38)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:57:9)
    at /var/tmp/worker/worker.js:689:7
    at /var/tmp/worker/worker.js:673:9
```

This is the starter am using 

[Firebase Nextjs Starter Used](https://github.com/jthegedus/firebase-functions-next-example
)
**Changes done to the Starter Project :** 

1. _Modified app.js as below_

```
import * as functions from "firebase-functions"
import next from "next"
import parse from "url"
import join from "path"
const dev = process.env.NODE_ENV !== "production"
const app = next({ dev, conf: { distDir: "next" } })
const handle = app.getRequestHandler()
const nextApp = functions.https.onRequest((request, response) => {
  console.log("File: " + request.originalUrl)
  console.log("dev:", dev)
  // log the page.js file or resource being requested
  const parsedUrl = parse(request.url, true)
  const { pathname } = parsedUrl
  console.log("pathname:", pathname)
  if (pathname === '/service-worker.js') {
    const filePath = join(__dirname, '.next', pathname)
    return app.serveStatic(request, response, filePath)
  } 
  return app.prepare().then(() => handle(request, response))
})
export { nextApp }
```

**_2. This is my next.config.js file_**

```
const withOffline = require('next-offline')
module.exports = {
  distDir: "../../dist/functions/next",
  withOffline:withOffline()
}
```

**Question :** 
1. How do i know if the service worker is working fine. Currently am trying to look for the sw.js file in Application tab in chrome console. 

2. Do I need to connect the component to load the service worker file ? 

**_My package.json file  :_** 

```
{
  "name": "firebase-functions-nextjs",
  "version": "2.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "firebase": "^5.5.3",
    "firebase-admin": "^5.12.1",
    "firebase-functions": "^2.0.5",
    "next": "^7.0.2",
    "next-offline": "^3.0.2",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "styled-jsx": "^3.1.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "@firebase/app-types": "^0.3.2",
    "cpx": "^1.5.0",
    "firebase-tools": "^3.18.6",
    "prettier": "^1.13.5",
    "rimraf": "^2.6.2"
  },
  "scripts": {
    "fblogin": "yarn firebase login",
    "dev": "next \"src/app\"",
    "preserve": "yarn build-public && yarn build-funcs && yarn build-app && yarn copy-deps && yarn install-deps",
    "serve": "NODE_ENV=production yarn firebase serve --only functions,hosting",
    "deploy-app": "yarn firebase deploy --only hosting,functions:app",
    "deploy-functions": "yarn firebase deploy --only functions:greetings",
    "deploy-all": "yarn firebase deploy",
    "clean": "rimraf \"dist/functions\" && rimraf \"dist/public\"",
    "build-public": "cpx \"src/public/**/*.*\" \"dist/public\" -C",
    "build-funcs": "babel \"src/functions\" --out-dir \"dist/functions\"",
    "build-app": "NODE_ENV=production next build \"src/app\"",
    "copy-deps": "cpx \"*{package.json,yarn.lock}\" \"dist/functions\"",
    "install-deps": "cd \"dist/functions\" && yarn"
  },
  "prettier": {
    "trailingComma": "es5"
  }
}

```

**Comment by 1nullpointer** [comment]
Thanks @hanford . That helped. 
Fixed that and some other minor errors and it started working with firebase .

This is the final code : 

**app.js :** 
```
import * as functions from "firebase-functions"
import next from "next"
import {parse} from "url"
import {join} from "path"

const dev = process.env.NODE_ENV !== "production"
const app = next({ dev, conf: { distDir: "next" } })
const handle = app.getRequestHandler()

const nextApp = functions.https.onRequest((request, response) => {
  console.log("File: " + request.originalUrl)
  console.log("dev:", dev)
  // log the page.js file or resource being requested
  const parsedUrl = parse(request.url, true)
  const {pathname} = parsedUrl;

  console.log("pathname:", pathname)

  if (pathname === '/service-worker.js') {
    const filePath = join(__dirname, '.next', pathname)

    return app.serveStatic(request, response, filePath)
  } 

  return app.prepare().then(() => handle(request, response))
})

export { nextApp }
 
```

**2. next.config.js**

```
const withOffline = require('next-offline')

module.exports = withOffline({
  distDir: "../../dist/functions/next",
})

```

<img width="1011" alt="screen shot 2018-10-19 at 6 36 20 pm" src="https://user-images.githubusercontent.com/15132811/47220007-1d1d8e00-d3ce-11e8-85cc-af0233d8c315.png">

**Comment by 1nullpointer** [comment]
It was all working fine , and now I see this error . Nothing changed .
Any particular reason ? 

SW registration failed:  TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

**Comment by hanford** [comment]
@1nullpointer service worker registration is automatically handled by `next-offline`.

Could you create a small repo where you can reproduce this problem so I can dig a little deeper? 🕵️‍♂️

**Comment by hanford** [comment]
it might also be worth pointing out that service workers have some added security measures. 

Take a look at the `Why is my service worker failing to register?` section:

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

**Comment by 1nullpointer** [comment]
ok, the file path for the service-worker was the root cause.
Closing the issue
