### ISSUE TITLE
ValidationError: "runtimeCaching" is not a supported parameter.

### ISSUE THREAD

**Issue by PatrickSachs** [hanford/next-offline#98]
If I use the "runtimeCaching" option under "workboxOpts" I am unable to build my project.

**- Issue and steps to reproduce.**

The following config

```js
// Service Worker
  dontAutoRegisterSw: true,
  generateSw: false,
  //devSwSrc: path.join(__dirname, "./.build/service-worker.js"),
  workboxOpts: {
    swDest: "./service-worker.js",
    swSrc: path.join(__dirname, "./service-worker/index.js"),
    importWorkboxFrom: "local",
    runtimeCaching: [
      {
        urlPattern: /.png$/,
        handler: 'cacheFirst'
      },
      {
        // TODO: Don't cache session
        urlPattern: /api/,
        handler: 'networkFirst',
        options: {
          cacheableResponse: {
            statuses: [0, 200],
            headers: {
              'x-service-worker': 'true'
            }
          }
        }
      }
    ]
   // Same Error with this:
    //runtimeCaching: [{ urlPattern: /^https?.*/, handler: 'networkFirst' }],
  }
```

**- Versions.**

3.2.2

**- Screenshots.** (Log in this case)

```log
patrick@PATRICK:~/Development/helios/git$ npm run build

> helios@1.0.0 build /home/patrick/Development/helios/git
> cross-env NODE_ENV=production next build

[10:26:40 PM] Compiling server
[10:26:40 PM] Compiling client
[10:26:43 PM] Compiled server in 3s
> Failed to build
{ ValidationError: "runtimeCaching" is not a supported parameter.
    at Object.exports.process (/home/patrick/Development/helios/git/node_modules/joi/lib/errors.js:190:19)
    at internals.Object._validateWithOptions (/home/patrick/Development/helios/git/node_modules/joi/lib/types/any/index.js:668:31)
    at internals.Object.validate (/home/patrick/Development/helios/git/node_modules/joi/lib/types/any/index.js:702:21)
    at module.exports (/home/patrick/Development/helios/git/node_modules/workbox-build/build/entry-points/options/validate.js:20:33)
    at _callee$ (/home/patrick/Development/helios/git/node_modules/workbox-build/build/entry-points/get-manifest.js:36:23)
    at tryCatch (/home/patrick/Development/helios/git/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/patrick/Development/helios/git/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/patrick/Development/helios/git/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/patrick/Development/helios/git/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/patrick/Development/helios/git/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/patrick/Development/helios/git/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/patrick/Development/helios/git/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at getManifest (/home/patrick/Development/helios/git/node_modules/workbox-build/build/entry-points/get-manifest.js:57:17)
    at InjectManifest._callee$ (/home/patrick/Development/helios/git/node_modules/workbox-webpack-plugin/build/inject-manifest.js:160:24)
    at tryCatch (/home/patrick/Development/helios/git/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
  isJoi: true,
  name: 'ValidationError',
  details:
   [ { message: '"runtimeCaching" is not a supported parameter.',
       path: [Array],
       type: 'object.allowUnknown',
       context: [Object] } ],
  _object: { runtimeCaching: [ [Object], [Object] ], globPatterns: [] },
  annotate: [Function] }
```

**- Expected.**

Compile since this option is used in the example and default options.

**- Actual.**

Throws an error during build, rendering me unable to use this option.

**- Link to your project.**

Private repository, I can try to create a minimal reproduction repo should you be unable to reproduce this issue on your end.

**- Browser name and version.**

Not relevant here, but for the sake of completeness: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36`

**Comment by hanford** [comment]
Would be great if you could create a repo where we can reproduce this error as it's working on my end 🙇‍♂️

**Comment by PatrickSachs** [comment]
I'll look into it as soon as possible. Thank you very much for you time.

**Comment by hanford** [comment]
Damn, sorry to hear that!
